language: android
android:
  components:
    - build-tools-23.0.1
    - android-22
    - extra-android-m2repository
    - extra-google-google_play_services

script:
  - ./gradlew assembleDebug connectedCheck

branches:
  only:
    - development
