language: android
android:
  components:
    - build-tools-21.1.2
    - android-22
    - extra-android-m2repository

script:
  - ./gradlew assembleDebug connectedCheck

branches:
  only:
    - development
